- hosts: sun
  vars:
    - DO_PSW: do007deAK47
    - WORK_PATH: /Users/junwu/develop/proj/sun/.pose/work
    - SERVICE_PATH: /Users/junwu/develop/proj/sun/.pose/service
    - DO_COMPOSE: /Users/junwu/develop/proj/sun/.pose/docker-compose
    - NGINX_PATH: /Users/junwu/develop/proj/sun/.pose/nginx
    - DO_USER_NAME: johnhaha
    - WORK_NAME: sun
    - APP_PATH: /Users/junwu/develop/proj/sun/.pose/app
    - WEB_PATH: /Users/junwu/develop/proj/sun/web
    - DO_REGISTRY: docker.io
    - SCRIPT_PATH: /Users/junwu/develop/deploy/shoot/scripts
  tasks:
    - command: uname -a
      name: uname task
      register: wfkwqt
    - debug:
        var: wfkwqt.stdout_lines
    - copy:
        dest: /home
        mode: u=rwx,g=rx,o=r
        src: '{{SCRIPT_PATH}}'
      name: copy script to server
      register: xdduum
    - debug:
        var: xdduum.stdout_lines
    - copy:
        dest: /home
        mode: u=rwx,g=rx,o=r
        src: '{{NGINX_PATH}}'
      name: copy nginx to server
      register: zzekhj
    - debug:
        var: zzekhj.stdout_lines
    - copy:
        dest: /usr/local/bin/docker-compose
        mode: u=rwx,g=rx,o=r
        src: '{{DO_COMPOSE}}'
      name: copy compose file to server
      register: rhzllc
    - debug:
        var: rhzllc.stdout_lines
    - command: chmod +x /usr/local/bin/docker-compose
      name: chmod compose
      register: mllzqe
    - debug:
        var: mllzqe.stdout_lines
    - command: chdir=/home/scripts ./install.sh
      name: run install task
      register: idhgpk
    - debug:
        var: idhgpk.stdout_lines
    - command: mv /home/nginx/nginx /etc/nginx/sites-enabled/default
      name: config nginx
      register: dasuin
    - debug:
        var: dasuin.stdout_lines
    - command: chdir=/home/scripts ./config.sh
      name: run config shell
      register: dqdrgm
    - debug:
        var: dqdrgm.stdout_lines
