- hosts: sun
  vars:
    - DO_COMPOSE: /Users/junwu/develop/proj/sun/.pose/docker-compose
    - NGINX_PATH: /Users/junwu/develop/proj/sun/.pose/nginx
    - DO_PSW: do007deAK47
    - SCRIPT_PATH: /Users/junwu/develop/deploy/shoot/scripts
    - DO_USER_NAME: johnhaha
    - APP_PATH: /Users/junwu/develop/proj/sun/.pose/app
    - SERVICE_PATH: /Users/junwu/develop/proj/sun/.pose/service
    - WEB_PATH: /Users/junwu/develop/proj/sun/web
    - DO_REGISTRY: docker.io
    - WORK_PATH: /Users/junwu/develop/proj/sun/.pose/work
    - WORK_NAME: sun
  tasks:
    - command: uname -a
      name: uname task
      register: wevmkp
    - debug:
        var: wevmkp.stdout_lines
    - copy:
        dest: /home
        mode: u=rwx,g=rx,o=r
        src: '{{NGINX_PATH}}'
      name: copy nginx to server
      register: zsevpn
    - debug:
        var: zsevpn.stdout_lines
    - command: mv /home/nginx/nginx /etc/nginx/sites-enabled/default
      name: config nginx
      register: tuespe
    - debug:
        var: tuespe.stdout_lines
    - command: nginx -t
      name: run nginx test
      register: nceroi
    - debug:
        var: nceroi.stdout_lines
    - command: nginx -s reload
      name: run nginx test
      register: mbjigo
    - debug:
        var: mbjigo.stdout_lines
